export const getUsers = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const searchUser = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const updateUser = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const deleteUser = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const anonymizeUserById = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const addUserRole = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const getUserRoles = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const getUserRoleById = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const updateMe = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const deleteMe = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}
export const anonymizeMe = async (req, res, next) => {
  try {
    // const result = await registerHandler(req.body)
    // res.status(201).json(result)
  } catch (err) {
    next(err)
  }
}